[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "emod-common"
dynamic = ["version"]
description = "PyPI distribution of EMOD for testing features common to all sim types"
license = "MIT"
authors = [
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[project.optional-dependencies]
docs = [
    "sphinxext.remoteliteralinclude~=0.4",
    "sphinx~=6.2",
    "pydata-sphinx-theme",
    "plantweb~=1.2",
    "sphinxcontrib-programoutput~=0.17",
    "myst-parser~=2.0",
    "pygithub~=1.57",
]
tests = [
]

[project.urls]
Documentation = "https://docs.idmod.org/projects/emod/en/latest/"
Repository = "https://github.com/EMOD-Hub/EMOD"
Issues = "https://github.com/EMOD-Hub/EMOD/issues"

[tool.setuptools.package-data]
"*" = ["*.zip"]

[tool.setuptools.dynamic]
version = {file = ["src/version"]}
